version: '2.19.0'

services:
  postgres:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: truck
    ports:
      - "5432:5432"

  app:
    container_name: 'truck-app'
    image: 'springboot-postgresql'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres